version: '3.3'

services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy.Dockerfile
    image: 'grpcweb:envoy'
    container_name: 'envoy'
    restart: always
    ports:
      - '8080:8080'
      - '9901:9901'
    command: ['/etc/envoy/envoy.yaml']
    depends_on:
      - yorkie
      - metis-server
  metis-server:
    image: 'reg.navercorp.com/metis/metis-server:latest'
    container_name: 'metis-server'
    command: [
      'server',
      '--mongo-connection-uri',
      'mongodb://mongo:27017',
      '--yorkie-rpc-addr',
      'yorkie:11101',
    ]
    restart: always
    ports:
      - '10118:10118'
      - '10119:10119'
    depends_on:
      - mongo
      - yorkie
  yorkie:
    image: 'yorkieteam/yorkie:0.1.5'
    container_name: 'yorkie'
    command: [
      'agent',
      '--mongo-connection-uri',
      'mongodb://mongo:27017',
      '--authorization-webhook-url',
      'http://host.docker.internal:10119/auth',
    ]
    restart: always
    ports:
      - '11101:11101'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    restart: always
    ports:
      - '27017:27017'
